"""Fixed versions for deterministic market-data processing."""

LOCAL_CSV_PROVIDER_VERSION = "local_csv@1"
LOCAL_PARQUET_PROVIDER_VERSION = "local_parquet@1"
SYNTHETIC_PROVIDER_VERSION = "synthetic@1"
SCHEMA_VERSION = "market-bar@1"
NORMALIZATION_RULES_VERSION = "a-share-daily-normalization@1"
QUALITY_RULES_VERSION = "a-share-daily-quality@1"
ISSUE_FINGERPRINT_VERSION = "quality-issue-sha256@2"
PREVIEW_FINGERPRINT_VERSION = "preview-sha256@1"
