from __future__ import annotations

from enum import StrEnum


class AIAnalysisStage(StrEnum):
    DIAGNOSIS = "DIAGNOSIS"
    RECOMMENDATION = "RECOMMENDATION"
    CONVERSATION = "CONVERSATION"


class AIAnalysisRunStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    VALIDATING = "VALIDATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class AIAnalysisAttemptStatus(StrEnum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ABANDONED = "ABANDONED"


class AITraceEventType(StrEnum):
    CASE_FROZEN = "CASE_FROZEN"
    PROMPT_RESOLVED = "PROMPT_RESOLVED"
    PROVIDER_ATTEMPT_STARTED = "PROVIDER_ATTEMPT_STARTED"
    PROVIDER_ATTEMPT_FAILED = "PROVIDER_ATTEMPT_FAILED"
    PROVIDER_ATTEMPT_COMPLETED = "PROVIDER_ATTEMPT_COMPLETED"
    RUN_FAILED = "RUN_FAILED"
    RUN_CANCELLED = "RUN_CANCELLED"
    RUN_COMPLETED = "RUN_COMPLETED"
