from __future__ import annotations

from enum import StrEnum


class PaperAccountStatus(StrEnum):
    ACTIVE = "ACTIVE"
    FROZEN = "FROZEN"


class PaperSessionStatus(StrEnum):
    CREATED = "CREATED"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    STOPPED = "STOPPED"
    FAILED = "FAILED"


class PaperOrderStatus(StrEnum):
    CREATED = "CREATED"
    RISK_REJECTED = "RISK_REJECTED"
    APPROVED = "APPROVED"
    SUBMITTED = "SUBMITTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    REJECTED = "REJECTED"


class IntentSourceType(StrEnum):
    STRATEGY = "STRATEGY"
    MANUAL = "MANUAL"


class RiskDecisionType(StrEnum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"


class RiskPolicyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class LedgerEntryType(StrEnum):
    INITIAL_DEPOSIT = "INITIAL_DEPOSIT"
    TRADE_SETTLEMENT = "TRADE_SETTLEMENT"
    FEE = "FEE"


class AdvanceStatus(StrEnum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class AuditEventType(StrEnum):
    ACCOUNT_CREATED = "ACCOUNT_CREATED"
    SESSION_CREATED = "SESSION_CREATED"
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_PAUSED = "SESSION_PAUSED"
    SESSION_ADVANCED = "SESSION_ADVANCED"
    SESSION_STOPPED = "SESSION_STOPPED"
    SESSION_FAILED = "SESSION_FAILED"
    INTENT_CREATED = "INTENT_CREATED"
    RISK_APPROVED = "RISK_APPROVED"
    RISK_REJECTED = "RISK_REJECTED"
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_PARTIALLY_FILLED = "ORDER_PARTIALLY_FILLED"
    ORDER_EXPIRED = "ORDER_EXPIRED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    ORDER_REJECTED = "ORDER_REJECTED"
    ACCOUNT_FROZEN = "ACCOUNT_FROZEN"
    ACCOUNT_UNFROZEN = "ACCOUNT_UNFROZEN"
    RISK_POLICY_VERSION_CREATED = "RISK_POLICY_VERSION_CREATED"
